spring.application.name=spring-evaluacion-final
spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.messages.encoding=UTF-8
server.error.whitelabel.enabled=false
jwt.secret=dGhpcyBpcyBhIHNlY3JldCBrZXkgZm9yIEpXVCBhdXRoZW50aWNhdGlvbiBpbiBTcHJpbmcgQm9vdCBhcHBsaWNhdGlvbiBmb3IgZXZhbHVhY2lvbiBmaW5hbA==
